import { createClient } from '@sanity/client'

const token = process.env.SANITY_API_TOKEN
if (!token) {
  console.error('\n❌  SANITY_API_TOKEN is not set.')
  console.error('    Run: npm run import-services')
  console.error('    (requires --env-file=.env.local flag via tsx)\n')
  process.exit(1)
}

const client = createClient({
  projectId: process.env.NEXT_PUBLIC_SANITY_PROJECT_ID ?? '98jwav2j',
  dataset: process.env.NEXT_PUBLIC_SANITY_DATASET ?? 'production',
  apiVersion: process.env.NEXT_PUBLIC_SANITY_API_VERSION ?? '2024-01-01',
  token,
  useCdn: false,
})

// Convention: no suffix = Indonesian (primary), En suffix = English
const services = [
  // ── TIER 1 (9 core services) ─────────────────────────────────────────
  {
    _id: 'service-corporate-event',
    _type: 'service',
    title: 'Corporate Event',
    titleId: 'Corporate Event',
    slug: { _type: 'slug', current: 'corporate-event' },
    number: '01/16',
    tier: 'tier1',
    descriptor: 'Format payung — annual leadership, kick-off, perayaan korporat berskala besar.',
    descriptorEn: 'The flagship format — annual leadership, kick-off, and large-scale corporate celebrations.',
    tagline: 'Ketika organisasi berkumpul — setiap momen harus bekerja.',
    problem: 'Event korporat gagal ketika diperlakukan sebagai kewajiban jadwal, bukan peluang strategis. Venue penuh, agenda padat — namun pesan utama tidak sampai dan peserta pulang tanpa perubahan nyata dalam cara mereka berpikir atau bekerja.',
    approach: 'Kami merancang corporate event sebagai lingkungan komunikasi strategis. Dari kick-off tahunan hingga town hall nasional, setiap elemen — urutan sesi, tata letak ruangan, momen transisi — dirancang untuk menggerakkan agenda bisnis tertentu ke depan.',
    included: [
      'Konsep penuh dan run-of-show acara',
      'Pemilihan dan manajemen venue',
      'Produksi panggung, AV, dan pencahayaan',
      'Desain perjalanan peserta dari registrasi hingga penutupan',
      'Manajemen pembicara dan narasumber',
      'Katering dan hospitality',
      'Dokumentasi foto dan video',
    ],
    idealFor: 'Perusahaan yang menggelar gathering tahunan, kick-off strategi, town hall eksekutif, atau perayaan pencapaian korporat — dari 100 hingga 5.000+ peserta.',
    faqs: [
      {
        _key: 'faq-ce-1',
        question: 'How far in advance should we book for a large corporate event?',
        questionId: 'Seberapa jauh sebelumnya kami harus memesan untuk corporate event besar?',
        answer: 'For events of 500+ attendees, we recommend engaging us at least 12–16 weeks before the date.',
        answerId: 'Untuk acara 500+ peserta, kami menyarankan keterlibatan minimal 12–16 minggu sebelum hari-H. Ini memberi waktu cukup untuk kontrak venue, kurasi pembicara, dan persiapan produksi penuh. Kami pernah mengelola acara dalam tenggat yang lebih singkat — tapi pilihan dan kualitas menyempit dengan cepat.',
      },
      {
        _key: 'faq-ce-2',
        question: 'Do you manage all vendors or do we need to source some separately?',
        questionId: 'Apakah Anda mengelola semua vendor atau kami perlu mencari sebagian secara terpisah?',
        answer: 'We act as a single point of accountability across all vendors.',
        answerId: 'Kami bertindak sebagai satu titik akuntabilitas di semua vendor — venue, katering, AV, dekorasi, dokumentasi, dan talent. Klien tidak perlu mengoordinasikan vendor secara terpisah; semua melapor melalui kami dengan standar yang sama.',
      },
      {
        _key: 'faq-ce-3',
        question: 'Does ELEVENT handle all vendors or do we need to source some ourselves?',
        questionId: 'Apakah Elevent menangani semua vendor atau kami perlu mencari sebagian sendiri?',
        answer: 'We handle everything end-to-end — one contact, one accountability. You do not need to coordinate with any vendor separately.',
        answerId: 'Kami menangani end-to-end — satu kontak, satu akuntabilitas. Anda tidak perlu koordinasi dengan vendor manapun secara terpisah. Semua vendor diseleksi dan dikelola oleh tim kami.',
      },
    ],
  },
  {
    _id: 'service-corporate-gathering',
    _type: 'service',
    title: 'Corporate Gathering',
    titleId: 'Corporate Gathering',
    slug: { _type: 'slug', current: 'corporate-gathering' },
    number: '02/16',
    tier: 'tier1',
    descriptor: 'Penyelarasan internal — townhall, family day, year-end engagement.',
    descriptorEn: 'Internal alignment — townhalls, family days, and year-end engagement.',
    tagline: 'Ruangan yang berbeda menghasilkan percakapan yang berbeda.',
    problem: 'Gathering korporat sering berakhir sebagai pengulangan suasana kantor dengan meja makan yang lebih besar. Informasi disampaikan, tapi koneksi antar manusia yang semestinya diperkuat justru diabaikan.',
    approach: 'Kami merancang gathering sebagai momen penyelarasan manusia — bukan sekadar agenda yang dikemas dalam ruangan baru. Format, energi, dan ritme acara dirancang untuk mempertemukan orang pada level yang tidak bisa dicapai dalam rapat mingguan.',
    included: [
      'Konsep dan tema gathering',
      'Manajemen venue dan logistik penuh',
      'Program acara dan fasilitasi',
      'Katering dan hospitality',
      'Hiburan dan aktivitas interaktif',
      'Dokumentasi foto dan video',
      'Perlengkapan dan souvenir branded',
    ],
    idealFor: 'Perusahaan yang menyelenggarakan family day, townhall nasional, year-end party, atau employee engagement gathering — untuk membangun koneksi yang tidak bisa dibangun melalui email.',
    faqs: [
      {
        _key: 'faq-cg-1',
        question: 'What is the difference between a corporate gathering and a corporate event?',
        questionId: 'Apa perbedaan antara corporate gathering dan corporate event?',
        answer: 'Corporate events tend to be more strategically structured; gatherings are more focused on human connection and internal culture.',
        answerId: 'Corporate event cenderung lebih terstruktur secara strategis — dengan agenda bisnis yang jelas dan ukuran keberhasilan yang terukur. Corporate gathering lebih berfokus pada koneksi manusia dan budaya internal — dari family day hingga year-end celebration. Keduanya membutuhkan desain yang serius untuk berhasil.',
      },
      {
        _key: 'faq-cg-2',
        question: 'Can you run gatherings for very large groups (1,000+ employees)?',
        questionId: 'Bisakah Anda menjalankan gathering untuk kelompok sangat besar (1.000+ karyawan)?',
        answer: 'Yes. We have produced gatherings for groups up to 5,000 people.',
        answerId: 'Ya. Kami telah memproduksi gathering untuk kelompok hingga 5.000 orang. Gathering besar memerlukan arsitektur program yang berbeda — kombinasi momen plenary bersama dan pengalaman yang lebih intim dalam subkelompok — sehingga setiap orang merasa hadir secara nyata, bukan sekadar hadir secara fisik.',
      },
      {
        _key: 'faq-cg-3',
        question: 'Can you organise gatherings that include employees\' families?',
        questionId: 'Apakah Anda bisa menangani gathering yang melibatkan keluarga karyawan?',
        answer: 'Yes. Family day is one of our most frequently produced formats.',
        answerId: 'Ya. Family day adalah salah satu format yang paling sering kami kerjakan. Program dirancang untuk melibatkan karyawan dan anggota keluarga mereka — dengan aktivitas yang relevan untuk berbagai kelompok usia dan latar belakang. Kami mengurus semua logistik keluarga, dari area bermain anak hingga titik pertemuan yang jelas.',
      },
    ],
  },
  {
    _id: 'service-product-launching',
    _type: 'service',
    title: 'Product Launching',
    titleId: 'Peluncuran Produk',
    slug: { _type: 'slug', current: 'product-launching' },
    number: '03/16',
    tier: 'tier1',
    descriptor: 'Momen perkenalan — strategi narasi, panggung, dan jurnalis dalam satu arsitektur.',
    descriptorEn: 'Product introduction moments — narrative, stage, and media in one architecture.',
    tagline: 'Kesan pertama yang menjadi momen pasar.',
    problem: 'Peluncuran produk adalah satu momen bertaruh tinggi yang entah meraih perhatian atau menghilang. Sebagian besar peluncuran mencampuradukkan pengumuman dengan dampak — mereka mengkomunikasikan fitur saat pasar mendengarkan makna.',
    approach: 'Kami membangun peluncuran produk sebagai narasi brand. Produk memasuki konteks yang telah kami ciptakan — suasana, ruangan, urutan reveal — dirancang agar jurnalis, mitra, dan pembeli merasakan signifikansinya sebelum memahami spesifikasinya.',
    included: [
      'Konsep dan kolateral teaser pra-peluncuran',
      'Desain venue atau lingkungan pop-up',
      'Desain pengalaman media dan tamu VIP',
      'Urutan reveal produk dan penataan panggung',
      'Setup pengambilan konten untuk pers dan media sosial',
      'Coaching MC dan presenter',
      'Koordinasi press kit pasca-acara',
    ],
    idealFor: 'Brand yang memperkenalkan produk, platform, atau arah pasar baru kepada media, mitra, key account, atau konsumen — saat persepsi pertama adalah segalanya.',
    faqs: [
      {
        _key: 'faq-pl-1',
        question: 'How do you handle media and press invitations?',
        questionId: 'Bagaimana Anda menangani undangan media dan pers?',
        answer: 'We coordinate the full media invitation and accreditation process alongside your PR team.',
        answerId: 'Kami mengkoordinasikan proses undangan media dan akreditasi penuh, bekerja bersama tim komunikasi atau PR agency Anda. Kami mengelola check-in media, zona pers khusus, penjadwalan wawancara, dan serah terima aset konten — memastikan jurnalis memiliki semua yang dibutuhkan untuk filing tepat waktu.',
      },
      {
        _key: 'faq-pl-2',
        question: 'How do you ensure product reveal secrecy before launch?',
        questionId: 'Bagaimana Anda memastikan kerahasiaan reveal produk sebelum peluncuran?',
        answer: 'Confidentiality is a production discipline for us — strict need-to-know protocols throughout.',
        answerId: 'Kerahasiaan adalah disiplin produksi bagi kami. Detail produk dibagikan secara ketat berdasarkan need-to-know dalam tim. Kami menggunakan protokol staging tersegel untuk akses venue, jalur briefing terpisah untuk kru, dan prosedur lockdown untuk lingkungan reveal.',
      },
      {
        _key: 'faq-pl-3',
        question: 'How early should we start planning a full-scale product launch?',
        questionId: 'Seberapa jauh sebelumnya persiapan peluncuran produk harus dimulai?',
        answer: 'For a full media launch, 10–14 weeks is our recommended lead time.',
        answerId: 'Untuk peluncuran skala media penuh, kami merekomendasikan 10–14 minggu. Ini mencakup fase teaser, koordinasi undangan media, desain venue, dan rehearsal presenter. Untuk peluncuran yang lebih terfokus, 6–8 minggu bisa cukup — tetapi semakin awal, semakin banyak opsi yang terbuka.',
      },
    ],
  },
  {
    _id: 'service-gala-dinner-award-night',
    _type: 'service',
    title: 'Gala Dinner & Award Night',
    titleId: 'Gala Dinner & Malam Penghargaan',
    slug: { _type: 'slug', current: 'gala-dinner-award-night' },
    number: '04/16',
    tier: 'tier1',
    descriptor: 'Malam selebrasi — koreografi penghargaan, hiburan, dan hospitality kelas eksekutif.',
    descriptorEn: 'Celebration evenings — award choreography, entertainment, and executive hospitality.',
    tagline: 'Malam di mana organisasi Anda mengingat dirinya sendiri.',
    problem: 'Acara tahunan sering diperlakukan sebagai kewajiban — makan malam, beberapa pidato, sebuah piagam. Hasilnya adalah malam yang terlupakan yang hampir tidak berdampak pada retensi, kebanggaan, atau budaya.',
    approach: 'Kami memperlakukan gala sebagai jangkar budaya. Malam ini dirancang untuk memunculkan nilai-nilai organisasi, mengakui pencapaiannya, dan membuat setiap peserta pulang dengan perasaan bahwa mereka adalah bagian dari sesuatu yang bermakna.',
    included: [
      'Konsep penuh malam, tema, dan identitas visual',
      'Transformasi venue dan desain atmosfer',
      'Produksi urutan penghargaan dan upacara',
      'Kurasi hiburan dan talent',
      'Manajemen tamu dan strategi tempat duduk',
      'Dokumentasi video dan foto',
      'Pemberian hadiah meja dan touchpoint branded',
    ],
    idealFor: 'Organisasi yang mengadakan upacara penghargaan tahunan, tonggak perusahaan, atau gala akhir tahun — di mana budaya, moral, dan identitas dipertaruhkan.',
    faqs: [
      {
        _key: 'faq-gd-1',
        question: 'How many awards categories can you manage in a single ceremony?',
        questionId: 'Berapa banyak kategori penghargaan yang bisa Anda kelola dalam satu upacara?',
        answer: 'We have produced ceremonies with 4 to 40+ award categories.',
        answerId: 'Kami telah memproduksi upacara dengan 4 hingga 40+ kategori penghargaan. Kuncinya adalah ritme — setiap kategori butuh waktu cukup untuk terasa bermakna tanpa kehilangan momentum malam. Kami menyusun skrip dan mewaktui setiap urutan terlebih dahulu dan melakukan rehearsal dengan semua presenter.',
      },
      {
        _key: 'faq-gd-2',
        question: 'Can you incorporate live entertainment within the ceremony?',
        questionId: 'Bisakah Anda memasukkan hiburan live dalam upacara?',
        answer: 'Yes. We curate and direct all entertainment to serve the evening\'s theme and emotional arc.',
        answerId: 'Ya. Kami mengkurasi dan mengarahkan semua hiburan — dari penampilan pembuka hingga pertunjukan setelah dinner — memastikan setiap elemen melayani tema dan busur emosional malam. Hiburan terintegrasi ke dalam run-of-show, bukan sekadar ditambahkan di belakang.',
      },
      {
        _key: 'faq-gd-3',
        question: 'What is the minimum and maximum guest count for a gala dinner?',
        questionId: 'Berapa jumlah tamu minimum dan maksimum untuk gala dinner?',
        answer: 'We have produced gala dinners from 80 to 1,500 guests.',
        answerId: 'Kami telah memproduksi gala dinner dari 80 hingga 1.500 tamu. Di bawah 80, pendekatan venue khusus yang lebih intim lebih masuk akal. Di atas 1.500, logistik layanan makan dan akustik panggung memerlukan perencanaan tambahan yang kami bangun sejak awal.',
      },
    ],
  },
  {
    _id: 'service-conference-seminar',
    _type: 'service',
    title: 'Conference & Seminar',
    titleId: 'Konferensi & Seminar',
    slug: { _type: 'slug', current: 'conference-seminar' },
    number: '05/16',
    tier: 'tier1',
    descriptor: 'Program multi-track — kurasi pembicara, alur sesi, dan ritme yang menjaga perhatian.',
    descriptorEn: 'Multi-track programmes — speaker curation, session flow, and rhythm that holds attention.',
    tagline: 'Di sinilah ide menjadi arah.',
    problem: 'Sebagian besar konferensi dijadwalkan, bukan dirancang. Pembicara berbicara kepada deretan peserta yang pasif. Informasi disampaikan tetapi jarang diserap. Pada hari kedua, perhatian sudah meninggalkan ruangan.',
    approach: 'Kami merancang konferensi sebagai lingkungan pengambilan keputusan. Setiap sesi, transisi, dan tata letak ruangan dirancang untuk memajukan agenda — dari tempat duduk yang menciptakan dialog hingga urutan penutupan yang menghasilkan keselarasan, bukan sekadar tepuk tangan.',
    included: [
      'Konsep penuh dan run-of-show konferensi',
      'Kurasi dan manajemen pembicara',
      'Produksi panggung, AV, dan pencahayaan',
      'Desain registrasi dan perjalanan peserta',
      'Fasilitasi sesi dan panel',
      'Manajemen breakout track paralel',
      'Dokumentasi ringkasan dan materi peserta',
    ],
    idealFor: 'Perusahaan dan asosiasi yang mengumpulkan 100–2.000+ profesional, eksekutif, atau pemangku kepentingan industri untuk berbagi pengetahuan, penyelarasan strategis, atau kepemimpinan pemikiran.',
    faqs: [
      {
        _key: 'faq-cs-1',
        question: 'How far in advance should we engage ELEVENT for a large conference?',
        questionId: 'Seberapa jauh sebelumnya kami harus melibatkan ELEVENT untuk konferensi besar?',
        answer: 'For conferences of 300+ attendees, we recommend engaging us at least 16 weeks before the event date.',
        answerId: 'Untuk konferensi 300+ peserta, kami menyarankan keterlibatan minimal 16 minggu sebelum hari-H. Ini memberi waktu cukup untuk kontrak venue, manajemen pembicara, dan persiapan produksi. Semakin awal keterlibatan, semakin strategis hasilnya.',
      },
      {
        _key: 'faq-cs-2',
        question: 'Can you handle multi-day conferences across multiple cities?',
        questionId: 'Bisakah Anda menangani konferensi multi-hari di beberapa kota?',
        answer: 'Yes. We have run multi-city roadshows across Jakarta, Surabaya, Bali, Singapore, and KL.',
        answerId: 'Kami telah melaksanakan roadshow multi-kota dan program berurutan di Jakarta, Surabaya, Bali, Singapura, dan Kuala Lumpur. Acara multi-lokasi memerlukan pemimpin operasional khusus di setiap kota — kami membangun ini ke dalam struktur tim sejak awal.',
      },
      {
        _key: 'faq-cs-3',
        question: 'Can you help curate and recruit speakers for our conference?',
        questionId: 'Apakah Anda bisa membantu kurasi dan merekrut pembicara untuk konferensi kami?',
        answer: 'Yes. Speaker curation is one of the highest-value services we provide.',
        answerId: 'Ya. Kurasi pembicara adalah salah satu nilai terbesar yang kami bawa. Kami memiliki jaringan pembicara lintas industri dan bisa membantu identifikasi, pendekatan awal, negosiasi honorarium, briefing konten, dan koordinasi logistik untuk semua pembicara — sehingga Anda tidak perlu mengelola setiap hubungan secara terpisah.',
      },
    ],
  },
  {
    _id: 'service-team-building',
    _type: 'service',
    title: 'Team Building',
    titleId: 'Team Building',
    slug: { _type: 'slug', current: 'team-building' },
    number: '06/16',
    tier: 'tier1',
    descriptor: 'Aktivitas dengan tujuan — bukan ice-breaker. Diukur dari hasil tim setelah event.',
    descriptorEn: 'Purposeful activities — not ice-breakers. Measured by team outcomes after the event.',
    tagline: 'Pengalaman bersama membangun apa yang rapat tidak bisa.',
    problem: 'Acara team building sering terasa dipaksakan karena memang dipaksakan. Pemikiran yang mendahulukan aktivitas menghasilkan acara yang ditoleransi, bukan diingat — dan jarang meningkatkan kohesi atau kinerja tim yang sebenarnya.',
    approach: 'Kami merancang team building di sekitar tujuan organisasi yang spesifik — baik itu penyelarasan lintas fungsi, integrasi pasca-restrukturisasi, atau membangun kembali modal sosial setelah periode sulit. Aktivitas melayani hasil.',
    included: [
      'Workshop penetapan tujuan bersama kepemimpinan',
      'Desain program dan aktivitas yang disesuaikan',
      'Koordinasi venue dan logistik',
      'Fasilitasi dan coaching tim',
      'Manajemen katering dan hospitality',
      'Dokumentasi foto dan video',
      'Survei refleksi dan umpan balik pasca-acara',
    ],
    idealFor: 'Tim 20–300 orang yang menavigasi perubahan, pertumbuhan, atau kebutuhan untuk bekerja lebih baik bersama — dari unit yang baru terbentuk hingga tim lama yang kehilangan kekuatannya.',
    faqs: [
      {
        _key: 'faq-tb-1',
        question: 'How do you ensure activities feel relevant rather than forced?',
        questionId: 'Bagaimana Anda memastikan aktivitas terasa relevan, bukan dipaksakan?',
        answer: 'We start every engagement with a diagnostic conversation with the commissioning leader.',
        answerId: 'Kami memulai setiap engagement dengan percakapan diagnostik bersama pemimpin yang menugaskan. Kami ingin memahami dinamika tim saat ini, apa yang telah dicoba sebelumnya, dan seperti apa hasil yang berhasil secara praktis. Aktivitas dipilih dan diurutkan untuk konteks spesifik itu — bukan dari katalog.',
      },
      {
        _key: 'faq-tb-2',
        question: 'Can you run programmes for very large teams (200+ people)?',
        questionId: 'Bisakah Anda menjalankan program untuk tim yang sangat besar (200+ orang)?',
        answer: 'Yes. We have produced team programmes for groups of up to 500.',
        answerId: 'Ya. Kami telah memproduksi program tim untuk kelompok hingga 500 orang, mempertahankan kualitas pengalaman di seluruh kelompok dengan desain track paralel dan stasiun aktivitas bergilir.',
      },
      {
        _key: 'faq-tb-3',
        question: 'Does team building need to be outdoors or can it happen inside?',
        questionId: 'Apakah program team building perlu dilakukan di luar kantor atau bisa di dalam gedung?',
        answer: 'Both are possible — the choice depends on the programme objectives.',
        answerId: 'Keduanya mungkin — dan pilihan tergantung pada tujuan program. Aktivitas di luar ruangan cenderung membangun energi dan melepas ketegangan kantor. Program indoor lebih mudah dikontrol dan bisa diintegrasikan ke dalam agenda hari kerja. Kami mendesain untuk kedua format dan merekomendasikan mana yang lebih sesuai setelah memahami konteks tim Anda.',
      },
    ],
  },
  {
    _id: 'service-mice-hospitality',
    _type: 'service',
    title: 'MICE & Hospitality',
    titleId: 'MICE & Hospitality',
    slug: { _type: 'slug', current: 'mice-hospitality' },
    number: '07/16',
    tier: 'tier1',
    descriptor: 'Meeting · incentive · convention · exhibition — operasi penuh untuk delegasi enterprise.',
    descriptorEn: 'Meeting · incentive · convention · exhibition — full operations for enterprise delegations.',
    tagline: 'MICE bukan sekadar logistik — ini adalah kesan yang Anda tinggalkan.',
    problem: 'Program MICE enterprise sering gagal di celah koordinasi — antara meeting organizer, hotel, vendor, dan klien. Standar tidak konsisten, akuntabilitas tidak jelas, dan delegasi internasional merasakan perbedaannya.',
    approach: 'Kami mengelola program MICE sebagai satu operasi terpadu — satu titik kontak, satu standar, dari pre-event planning hingga post-event reporting. Setiap aspek dirancang untuk mencerminkan standar klien enterprise yang kami layani.',
    included: [
      'Manajemen program penuh (meeting, incentive, convention, exhibition)',
      'Negosiasi dan manajemen venue serta hotel',
      'Transportasi dan logistik delegasi',
      'Katering dan hospitality eksekutif',
      'Manajemen vendor dan koordinasi on-site',
      'Dokumentasi dan pelaporan program',
      'Manajemen peserta internasional',
    ],
    idealFor: 'Perusahaan multinasional, asosiasi industri, dan organisasi yang menyelenggarakan program MICE dengan delegasi enterprise — di mana standar eksekusi dan reputasi perusahaan sedang dipertaruhkan.',
    faqs: [
      {
        _key: 'faq-mh-1',
        question: 'Do you manage MICE programmes that span multiple countries?',
        questionId: 'Apakah Anda mengelola program MICE yang mencakup beberapa negara?',
        answer: 'Yes. We have managed MICE programmes across Southeast Asia and beyond.',
        answerId: 'Ya. Kami telah mengelola program MICE di berbagai negara Asia Tenggara — mengoordinasikan logistik lintas batas, vendor lokal, dan standar pelayanan yang konsisten di setiap lokasi. Untuk program multi-negara, kami membangun tim dengan pemimpin operasional di setiap pasar.',
      },
      {
        _key: 'faq-mh-2',
        question: 'Can you handle incentive programmes for hundreds of delegates simultaneously?',
        questionId: 'Bisakah Anda menangani program insentif untuk ratusan delegasi secara bersamaan?',
        answer: 'Yes. Large-scale incentive programmes are one of our core specialisations.',
        answerId: 'Ya. Program insentif skala besar adalah salah satu spesialisasi inti kami. Kami telah mengelola program insentif untuk 50 hingga 500+ delegasi secara bersamaan, dengan logistik kelompok, pengalaman yang dipersonalisasi per tier, dan standar kualitas yang konsisten di seluruh program.',
      },
      {
        _key: 'faq-mh-3',
        question: 'How do you maintain consistent service quality across all MICE locations?',
        questionId: 'Bagaimana Anda menjaga kualitas layanan yang konsisten di semua lokasi program MICE?',
        answer: 'We set documented service standards and travel our core team with every programme.',
        answerId: 'Kami menetapkan standar layanan yang terdokumentasi untuk setiap program dan melatih tim lokal sebelum eksekusi. Satu program director kami hadir di seluruh perjalanan program dan bertanggung jawab atas konsistensi standar. Semua vendor lokal melewati proses seleksi dan orientasi sebelum terlibat dalam program klien.',
      },
    ],
  },
  {
    _id: 'service-hybrid-virtual-event',
    _type: 'service',
    title: 'Hybrid & Virtual Event',
    titleId: 'Acara Hybrid & Virtual',
    slug: { _type: 'slug', current: 'hybrid-virtual-event' },
    number: '08/16',
    tier: 'tier1',
    descriptor: 'Kualitas broadcast — audiens jarak jauh diperlakukan sebagai audiens utama, bukan tambahan.',
    descriptorEn: 'Broadcast quality — remote audiences treated as the primary audience.',
    tagline: 'Satu acara. Tidak ada audiens yang tertinggal.',
    problem: 'Acara hybrid biasanya tidak melayani audiens mana pun dengan baik. Ruangan fisik terganggu oleh logistik produksi; audiens jarak jauh adalah renungan belakangan. Hasilnya adalah kompromi yang buruk konversinya untuk kedua tujuan.',
    approach: 'Kami merancang acara hybrid sebagai dua pengalaman native yang berbagi momen, bukan satu acara dengan kamera di belakang. Audiens jarak jauh dan di dalam ruangan memiliki perjalanan berbeda yang bertemu di puncak yang dikoreografikan.',
    included: [
      'Desain pengalaman dual-audience',
      'Produksi broadcast dan live streaming',
      'Integrasi platform digital interaktif',
      'Manajemen produksi dan AV dalam ruangan',
      'Host dan moderasi jarak jauh',
      'Rehearsal teknis dan perencanaan kontingensi',
      'Perekaman on-demand dan distribusi',
    ],
    idealFor: 'Organisasi dengan tim terdistribusi, audiens regional, atau pemangku kepentingan internasional — di mana kehadiran fisik terbatas tetapi keterlibatan tidak bisa.',
    faqs: [
      {
        _key: 'faq-hv-1',
        question: 'Which streaming platforms do you support?',
        questionId: 'Platform streaming apa yang Anda dukung?',
        answer: 'We work across YouTube Live, Zoom Webinar, Hopin, Teams Live Events, and custom RTMP destinations.',
        answerId: 'Kami bekerja di semua platform utama — YouTube Live, Zoom Webinar, Hopin, Teams Live Events, dan tujuan RTMP kustom. Pemilihan platform didorong oleh infrastruktur klien yang ada, ukuran audiens, dan fitur interaktivitas yang dibutuhkan.',
      },
      {
        _key: 'faq-hv-2',
        question: 'What happens if the connection drops during a live stream?',
        questionId: 'Apa yang terjadi jika koneksi terputus saat live stream?',
        answer: 'We build full redundancy into every broadcast — primary and backup connections, hardware failover.',
        answerId: 'Kami membangun redundansi penuh ke dalam setiap siaran live — koneksi internet utama dan cadangan, encoder hardware dengan failover, dan technical director khusus yang memantau stream secara real time. Protokol kontingensi kami sudah dipelatihkan, bukan diimprovisasi.',
      },
      {
        _key: 'faq-hv-3',
        question: 'How much lead time is needed to produce a full hybrid event?',
        questionId: 'Berapa lama waktu yang dibutuhkan untuk memproduksi acara hybrid berkualitas?',
        answer: 'For a full broadcast-quality hybrid event, we recommend 8–10 weeks minimum.',
        answerId: 'Untuk acara hybrid dengan produksi broadcast penuh, kami merekomendasikan minimal 8–10 minggu persiapan. Ini mencakup seleksi platform, setup teknis, rehearsal multi-kamera, dan briefing presenter. Rehearsal teknis adalah bagian kritis yang tidak bisa dipersingkat — di sinilah sebagian besar masalah teknis ditemukan dan diselesaikan sebelum hari-H.',
      },
    ],
  },
  {
    _id: 'service-incentive-trip',
    _type: 'service',
    title: 'Incentive Trip',
    titleId: 'Incentive Trip',
    slug: { _type: 'slug', current: 'incentive-trip' },
    number: '09/16',
    tier: 'tier1',
    descriptor: 'Program penghargaan multi-hari — naratif, lokasi, dan pengalaman yang diingat bertahun-tahun.',
    descriptorEn: 'Multi-day reward programmes — destinations, narrative, and experiences remembered for years.',
    tagline: 'Hadiah terbaik adalah pengalaman yang tidak bisa dibeli sendiri.',
    problem: 'Perjalanan insentif yang gagal adalah yang terasa seperti paket wisata biasa dengan rompi berlogo perusahaan. Peserta menikmati liburannya — tapi kembali tanpa motivasi yang diperbarui atau loyalitas yang diperkuat.',
    approach: 'Kami merancang incentive trip sebagai narasi penghargaan yang imersif. Destinasi, aktivitas, dan momen-momen dalam perjalanan dirancang untuk menceritakan satu kisah: bahwa pencapaian mereka diakui, dihargai, dan diingat oleh organisasi.',
    included: [
      'Seleksi destinasi dan konsep perjalanan',
      'Koordinasi akomodasi dan transportasi',
      'Desain program aktivitas dan pengalaman',
      'Manajemen peserta dan logistik grup',
      'Private dining dan pengalaman kuliner',
      'Dokumentasi foto dan video perjalanan',
      'Koordinasi dengan vendor lokal dan otoritas setempat',
    ],
    idealFor: 'Perusahaan yang memberikan penghargaan kepada top performer, high achiever, atau dealer terbaik melalui perjalanan — di mana pengalaman harus setara dengan pencapaian yang dihargai.',
    faqs: [
      {
        _key: 'faq-it-1',
        question: 'What destinations do you specialise in for incentive trips?',
        questionId: 'Destinasi apa yang Anda spesialisasikan untuk incentive trip?',
        answer: 'Bali, Singapore, Bangkok, and Japan are our most requested; we can execute globally.',
        answerId: 'Bali, Singapura, Bangkok, dan Jepang adalah destinasi yang paling banyak diminta. Kami memiliki jaringan vendor dan relasi lokal yang kuat di destinasi-destinasi ini untuk memastikan pengalaman yang melebihi ekspektasi. Kami juga bisa mengeksekusi ke destinasi global lainnya dengan persiapan yang memadai.',
      },
      {
        _key: 'faq-it-2',
        question: 'Can you manage tiered incentive experiences within the same programme?',
        questionId: 'Bisakah Anda mengelola pengalaman insentif berjenjang dalam program yang sama?',
        answer: 'Yes. We design differentiated experiences for different achiever tiers within one cohesive programme.',
        answerId: 'Ya. Kami merancang pengalaman yang dibedakan untuk berbagai tier pencapaian dalam satu program yang kohesif — akomodasi yang berbeda, pengalaman eksklusif untuk tier teratas, dan pengakuan yang terasa singular untuk setiap penerima, tanpa ada kelompok yang merasa kelas dua.',
      },
      {
        _key: 'faq-it-3',
        question: 'What is the minimum group size for an incentive trip?',
        questionId: 'Berapa ukuran grup minimum untuk program incentive trip?',
        answer: 'We typically work with groups of 15 or more for dedicated incentive trip programmes.',
        answerId: 'Kami biasanya bekerja dengan grup minimal 15 orang. Di bawah itu, perjalanan reguler melalui agen perjalanan premium lebih efisien. Untuk grup yang lebih besar, model platform kami memungkinkan negosiasi yang lebih baik dengan properti dan operator lokal, menciptakan nilai yang tidak bisa didapat secara individual.',
      },
    ],
  },

  // ── TIER 2 (7 supporting services) ──────────────────────────────────
  {
    _id: 'service-corporate-meeting',
    _type: 'service',
    title: 'Corporate Meeting',
    titleId: 'Corporate Meeting',
    slug: { _type: 'slug', current: 'corporate-meeting' },
    number: '10/16',
    tier: 'tier2',
    descriptor: 'Ruang rapat yang dirancang untuk mendukung percakapan dan keputusan penting.',
    descriptorEn: 'Meeting environments designed to support important conversations and decisions.',
    tagline: 'Pertemuan yang produktif dimulai dari ruangan yang tepat.',
    problem: 'Rapat korporat penting sering diadakan di ruang yang tidak mendukung tujuannya. Kursi yang salah, suara yang bocor, teknologi yang tidak berfungsi — dan keputusan besar dicoba dibuat dalam kondisi yang salah.',
    approach: 'Kami mengelola corporate meeting sebagai layanan lingkungan dan pengalaman — dari seleksi ruang yang tepat, setup teknis yang mulus, hingga hospitality yang menjaga perhatian tetap tajam sepanjang sesi.',
    included: [
      'Seleksi dan manajemen venue rapat',
      'Setup AV dan teknologi konferensi',
      'Katering dan hospitality sesi',
      'Koordinasi logistik peserta',
      'Dokumentasi dan notulensi profesional',
      'Manajemen on-site penuh',
    ],
    idealFor: 'Tim eksekutif, board meeting, strategy session, atau pertemuan klien penting yang membutuhkan lingkungan yang mendukung kualitas percakapan dan pengambilan keputusan.',
    faqs: [
      {
        _key: 'faq-cm-1',
        question: 'Do you manage venue sourcing or only on-site operations?',
        questionId: 'Apakah Anda mengelola pencarian venue atau hanya operasional on-site?',
        answer: 'Both. We source, negotiate, and manage the venue as well as run all on-site logistics.',
        answerId: 'Keduanya. Kami mencari, bernegosiasi, dan mengelola venue — termasuk semua logistik on-site. Untuk pertemuan penting, pilihan venue adalah keputusan strategis: ruang yang tepat menentukan kualitas percakapan yang terjadi di dalamnya.',
      },
      {
        _key: 'faq-cm-2',
        question: 'What types of meeting venues do you typically recommend?',
        questionId: 'Jenis venue rapat apa yang biasanya Anda rekomendasikan?',
        answer: 'It depends on the meeting objective — we match venue type to conversation type.',
        answerId: 'Tergantung pada tujuan meeting. Board meeting strategis biasanya paling baik di ruang privat hotel bintang lima dengan setup yang memungkinkan percakapan melingkar. Off-site strategy session sering mendapat manfaat dari lingkungan yang lebih santai — resor atau villa privat. Kami mengevaluasi konteks dan merekomendasikan opsi yang paling mendukung kualitas percakapan yang Anda butuhkan.',
      },
      {
        _key: 'faq-cm-3',
        question: 'Can you document outcomes and decisions from the meeting?',
        questionId: 'Apakah Anda bisa mendokumentasikan hasil dan keputusan dari rapat?',
        answer: 'Yes. We provide structured note-taking, decision summaries, and action item documents.',
        answerId: 'Ya. Kami menyediakan layanan dokumentasi profesional termasuk notulensi terstruktur, ringkasan keputusan, dan dokumen action item. Untuk rapat yang membutuhkan kerahasiaan tinggi, protokol dokumentasi khusus tersedia, termasuk opsi tanpa perangkat digital.',
      },
    ],
  },
  {
    _id: 'service-corporate-anniversary',
    _type: 'service',
    title: 'Corporate Anniversary',
    titleId: 'Peringatan Korporat',
    slug: { _type: 'slug', current: 'corporate-anniversary' },
    number: '11/16',
    tier: 'tier2',
    descriptor: 'Peringatan tonggak perusahaan — dari satu dekade hingga satu abad.',
    descriptorEn: 'Company milestone celebrations — from one decade to one century.',
    tagline: 'Setiap tonggak layak diceritakan dengan cara yang tepat.',
    problem: 'Peringatan perusahaan sering menjadi nostalgia tanpa arah. Foto lama, pidato panjang, kue berlapis — dan karyawan pulang tanpa mengerti mengapa tonggak ini penting bagi masa depan, bukan hanya masa lalu.',
    approach: 'Kami merancang peringatan korporat sebagai jembatan antara warisan dan visi. Malam ini dirancang untuk menghormati yang telah dicapai, menghidupkan kembali nilai-nilai yang masih relevan, dan meluncurkan babak berikutnya dengan momentum.',
    included: [
      'Konsep tema dan identitas visual peringatan',
      'Program malam dan urutan upacara',
      'Produksi konten sejarah (video, timeline, galeri)',
      'Hiburan dan pertunjukan tematik',
      'Manajemen tamu dan undangan',
      'Dokumentasi foto dan video resmi',
      'Cendera mata dan kolateral peringatan',
    ],
    idealFor: 'Perusahaan yang merayakan 10, 25, 50 tahun atau lebih — di mana peringatan harus bermakna bagi karyawan, klien, dan pemangku kepentingan sekaligus.',
    faqs: [
      {
        _key: 'faq-ca-1',
        question: 'How do you balance looking back at history while also looking forward?',
        questionId: 'Bagaimana Anda menyeimbangkan melihat ke belakang pada sejarah sambil juga melihat ke depan?',
        answer: 'We design the narrative arc deliberately — heritage first, then pivot to vision.',
        answerId: 'Kami merancang busur narasi secara sengaja: penghormatan warisan di paruh pertama malam, kemudian pivot yang jelas ke visi di paruh kedua. Titik pivot itu — saat ruangan bergerak dari nostalgia ke aspirasi — adalah momen paling penting yang kami rancang dengan paling hati-hati.',
      },
      {
        _key: 'faq-ca-2',
        question: 'How far in advance should we start planning a corporate anniversary?',
        questionId: 'Seberapa jauh sebelumnya kami harus mulai merencanakan peringatan korporat?',
        answer: 'For major milestones (25, 50, 100 years), we recommend starting 6–12 months out.',
        answerId: 'Untuk peringatan besar (25, 50, atau 100 tahun), kami merekomendasikan memulai perencanaan 6–12 bulan sebelumnya. Peringatan yang baik membutuhkan riset sejarah, kurasi konten, dan waktu untuk membangun narasi yang otentik. Peringatan yang direncanakan terburu-buru terasa terburu-buru — dan tonggak seperti ini layak mendapat lebih dari itu.',
      },
      {
        _key: 'faq-ca-3',
        question: 'Do you help produce heritage content like anniversary books or documentaries?',
        questionId: 'Apakah Anda membantu produksi konten sejarah seperti buku atau film dokumenter?',
        answer: 'Yes. Heritage content production is an integral part of the anniversaries we design.',
        answerId: 'Ya. Produksi konten warisan adalah bagian integral dari peringatan yang kami rancang — mulai dari video dokumenter singkat, instalasi timeline interaktif, buku peringatan, hingga galeri digital. Kami bekerja dengan tim kreatif dan jurnalis terverifikasi untuk mengubah sejarah perusahaan menjadi narasi yang layak diceritakan.',
      },
    ],
  },
  {
    _id: 'service-corporate-outing',
    _type: 'service',
    title: 'Corporate Outing',
    titleId: 'Corporate Outing',
    slug: { _type: 'slug', current: 'corporate-outing' },
    number: '12/16',
    tier: 'tier2',
    descriptor: 'Satu hari di luar kantor yang dirancang untuk tim Anda secara spesifik.',
    descriptorEn: 'One day outside the office, specifically designed for your team.',
    tagline: 'Keluar dari kantor. Masuk ke dalam tim.',
    problem: 'Outing korporat yang gagal adalah yang terasa seperti obligasi HR — aktivitas generik yang sama yang dilakukan setiap departemen setiap tahun. Peserta hadir tapi tidak terlibat.',
    approach: 'Kami merancang outing sebagai pengalaman yang dipersonalisasi untuk tim Anda — dipilih berdasarkan dinamika tim, tujuan yang ingin dicapai, dan musim. Bukan paket jadi, tapi program yang dirancang untuk kelompok spesifik ini.',
    included: [
      'Seleksi aktivitas dan destinasi yang disesuaikan',
      'Koordinasi transportasi dan logistik',
      'Fasilitasi program dan aktivitas',
      'Katering dan meal management',
      'Perlengkapan dan safety briefing',
      'Dokumentasi foto',
      'Post-outing summary',
    ],
    idealFor: 'Tim divisi, departemen, atau unit bisnis yang membutuhkan hari yang bermakna di luar rutinitas kantor — untuk kohesi, relaksasi yang bertujuan, atau sekadar ingatan bersama yang baik.',
    faqs: [
      {
        _key: 'faq-co-1',
        question: 'What types of outing activities do you offer?',
        questionId: 'Jenis aktivitas outing apa yang Anda tawarkan?',
        answer: 'We curate activities based on your team\'s profile — from adventure to cultural to culinary experiences.',
        answerId: 'Kami mengkurasi aktivitas berdasarkan profil tim Anda — dari petualangan alam, pengalaman kuliner, aktivitas kreatif, hingga pengalaman budaya lokal. Tidak ada paket standar; setiap outing dimulai dari percakapan tentang siapa tim Anda dan apa yang ingin dicapai.',
      },
      {
        _key: 'faq-co-2',
        question: 'Which locations do you work with for corporate outings?',
        questionId: 'Di mana saja Anda menyelenggarakan outing korporat?',
        answer: 'Across Indonesia — from Puncak and Lembang to Bali, Lombok, and Yogyakarta.',
        answerId: 'Di seluruh Indonesia — dari Puncak, Lembang, dan Karawang untuk grup Jabodetabek, hingga Bali, Lombok, dan Yogyakarta untuk outing multi-hari. Kami juga memiliki jejaring untuk destinasi Asia Tenggara bagi perusahaan yang ingin outing internasional.',
      },
      {
        _key: 'faq-co-3',
        question: 'What is the optimal group size for a corporate outing?',
        questionId: 'Berapa ukuran grup yang optimal untuk outing korporat?',
        answer: 'We manage outings from 20 to 500 people.',
        answerId: 'Kami menangani outing dari 20 hingga 500 orang. Grup di bawah 100 orang biasanya memungkinkan desain yang lebih personal dan aktivitas yang lebih intimate. Untuk grup lebih besar, kami memecah program ke dalam subkelompok yang bergantian melalui stasiun aktivitas — memastikan kualitas pengalaman tetap tinggi di seluruh grup.',
      },
    ],
  },
  {
    _id: 'service-brand-activation',
    _type: 'service',
    title: 'Brand Activation',
    titleId: 'Aktivasi Brand',
    slug: { _type: 'slug', current: 'brand-activation' },
    number: '13/16',
    tier: 'tier2',
    descriptor: 'Aktivasi yang mengubah kehadiran menjadi keterlibatan nyata dan ingatan yang bertahan.',
    descriptorEn: 'Activations that convert presence into genuine engagement and lasting memory.',
    tagline: 'Ubah kehadiran menjadi partisipasi.',
    problem: 'Aktivasi brand gagal ketika memprioritaskan spektakel atas keterlibatan. Keramaian bukan berarti koneksi. Sebagian besar aktivasi difoto dan dilupakan dalam hitungan jam.',
    approach: 'Kami merancang aktivasi sebagai pengalaman brand yang partisipatif. Pengunjung bukan penonton — mereka berperan. Setiap interaksi dirancang untuk menciptakan kenangan yang milik brand, bukan feed Instagram.',
    included: [
      'Desain konsep dan pengalaman',
      'Desain ruang dan instalasi',
      'Integrasi narasi dan pesan brand',
      'Briefing kru dan talent',
      'Manajemen perjalanan dan alur pengunjung',
      'Setup pengambilan konten',
      'Laporan pasca-aktivasi dan analisis jangkauan',
    ],
    idealFor: 'Brand dengan kehadiran di acara publik, expo, mal, atau pengalaman yang dimiliki — di mana tujuannya adalah waktu tinggal, koneksi emosional, dan earned media.',
    faqs: [
      {
        _key: 'faq-ba-1',
        question: 'How do you measure activation success?',
        questionId: 'Bagaimana Anda mengukur keberhasilan aktivasi?',
        answer: 'We define success metrics with the client before design begins.',
        answerId: 'Kami mendefinisikan metrik keberhasilan bersama klien sebelum desain dimulai — biasanya kombinasi waktu tinggal, tingkat interaksi, volume pengambilan konten, dan konversi lead. Kami membangun mekanisme pengukuran ke dalam aktivasi sejak awal.',
      },
      {
        _key: 'faq-ba-2',
        question: 'Do you design the physical build or just the concept?',
        questionId: 'Apakah Anda mendesain pembangunan fisik atau hanya konsepnya?',
        answer: 'Both — concept through construction, with ELEVENT as the single point of accountability.',
        answerId: 'Keduanya — dari konsep hingga konstruksi, dengan ELEVENT sebagai satu titik akuntabilitas. Kami merancang pengalaman pengunjung, menentukan spesifikasi pembangunan fisik, dan mengelola fabrikasi dan instalasi dengan mitra produksi kami.',
      },
      {
        _key: 'faq-ba-3',
        question: 'How much lead time does a brand activation require?',
        questionId: 'Seberapa jauh sebelumnya aktivasi harus direncanakan?',
        answer: 'For activations with complex physical builds, 8–10 weeks is our recommended lead time.',
        answerId: 'Untuk aktivasi dengan pembangunan fisik yang kompleks, kami merekomendasikan minimal 8–10 minggu. Ini mencakup desain, persetujuan klien, fabrikasi, dan instalasi. Aktivasi yang lebih sederhana bisa dilaksanakan dalam 4–6 minggu. Keterlibatan awal juga membuka pilihan venue dan talent premium yang sering habis jauh sebelum tanggal pelaksanaan.',
      },
    ],
  },
  {
    _id: 'service-exhibition-pameran',
    _type: 'service',
    title: 'Exhibition & Pameran',
    titleId: 'Exhibition & Pameran',
    slug: { _type: 'slug', current: 'exhibition-pameran' },
    number: '14/16',
    tier: 'tier2',
    descriptor: 'Kehadiran pameran yang dirancang untuk menarik dan mengkonversi, bukan sekadar memajang.',
    descriptorEn: 'Exhibition presence designed to attract and convert, not merely display.',
    tagline: 'Di antara ratusan booth — jadilah yang diingat.',
    problem: 'Booth pameran yang gagal adalah yang dirancang seperti brosur tiga dimensi. Pengunjung melihat, membaca, dan berlalu. Tidak ada percakapan yang dimulai, tidak ada lead yang tertangkap, tidak ada kesan yang bertahan.',
    approach: 'Kami merancang kehadiran exhibition sebagai pengalaman — bukan display. Dari konsep booth, alur pengunjung, hingga aktivasi di dalam booth, setiap elemen dirancang untuk memulai percakapan yang tepat dengan orang yang tepat.',
    included: [
      'Desain konsep dan visual booth',
      'Konstruksi dan instalasi booth',
      'Desain alur dan pengalaman pengunjung',
      'Materi dan kolateral promosi',
      'Briefing dan manajemen tim booth',
      'Sistem penangkapan lead',
      'Dokumentasi dan laporan pasca-pameran',
    ],
    idealFor: 'Perusahaan yang berpartisipasi dalam trade show, pameran industri, atau expo — di mana tujuannya adalah menghasilkan lead, membangun awareness, atau memperkuat posisi pasar.',
    faqs: [
      {
        _key: 'faq-ep-1',
        question: 'What booth sizes do you typically work with?',
        questionId: 'Ukuran booth apa yang biasanya Anda tangani?',
        answer: 'We work with booths from 9m² to 300m² custom builds.',
        answerId: 'Kami bekerja dengan booth dari 9m² hingga custom build 300m² dan lebih. Ukuran bukanlah variabel terpenting — desain pengalaman pengunjung di dalam ruang yang tersedia adalah yang menentukan apakah booth Anda menghasilkan percakapan atau tidak.',
      },
      {
        _key: 'faq-ep-2',
        question: 'Do you manage registration and coordination with exhibition organisers?',
        questionId: 'Apakah Anda juga mengelola proses pendaftaran dan koordinasi dengan penyelenggara pameran?',
        answer: 'Yes. We handle the full coordination with exhibition organisers from registration through teardown.',
        answerId: 'Ya. Kami mengelola seluruh proses koordinasi dengan penyelenggara pameran — pendaftaran booth, pengajuan gambar teknis, koordinasi listrik dan IT, serta compliance dengan regulasi venue. Ini adalah pekerjaan yang memakan waktu dan sering diabaikan sampai terlambat; kami mengurusnya sejak awal.',
      },
      {
        _key: 'faq-ep-3',
        question: 'Can you design a booth system that works across multiple exhibitions?',
        questionId: 'Bisakah Anda merancang booth yang bisa digunakan di beberapa pameran?',
        answer: 'Yes. We design modular booth systems that reconfigure for different footprints and layouts.',
        answerId: 'Ya. Kami merancang sistem booth modular yang bisa dikonfigurasi ulang untuk ukuran dan tata letak yang berbeda di pameran yang berbeda. Ini memaksimalkan nilai investasi pembangunan dan memastikan tampilan brand yang konsisten di semua kehadiran pameran Anda sepanjang tahun.',
      },
    ],
  },
  {
    _id: 'service-roadshow',
    _type: 'service',
    title: 'Roadshow',
    titleId: 'Roadshow',
    slug: { _type: 'slug', current: 'roadshow' },
    number: '15/16',
    tier: 'tier2',
    descriptor: 'Program multi-kota dengan standar yang konsisten di setiap titik.',
    descriptorEn: 'Multi-city programmes with consistent standards at every stop.',
    tagline: 'Satu pesan. Banyak kota. Standar yang sama.',
    problem: 'Roadshow gagal ketika setiap kota terasa seperti acara yang berbeda — kualitas yang tidak konsisten, pesan yang terdilusi, dan audiens di kota ke-3 mendapat pengalaman yang lebih buruk dari kota ke-1.',
    approach: 'Kami mengelola roadshow sebagai satu program yang diekspresikan di banyak lokasi — dengan standar produksi, pesan, dan pengalaman yang identik dari kota pertama hingga kota terakhir. Adaptasi lokal dibuat tanpa mengorbankan konsistensi.',
    included: [
      'Perencanaan rute dan jadwal multi-kota',
      'Manajemen venue di setiap kota',
      'Logistik pergerakan tim dan peralatan',
      'Produksi standar di setiap lokasi',
      'Manajemen peserta lokal dan registrasi',
      'Koordinasi media lokal',
      'Pelaporan komprehensif per kota',
    ],
    idealFor: 'Brand dan perusahaan yang ingin menjangkau audiens di beberapa kota dalam satu program terkoordinasi — untuk peluncuran produk, sosialisasi kebijakan, atau kampanye engagement regional.',
    faqs: [
      {
        _key: 'faq-rs-1',
        question: 'How many cities can a roadshow cover?',
        questionId: 'Berapa banyak kota yang bisa dicakup oleh roadshow?',
        answer: 'We have run roadshows covering 3 to 15 cities across Indonesia and Southeast Asia.',
        answerId: 'Kami telah menjalankan roadshow yang mencakup 3 hingga 15 kota di Indonesia dan Asia Tenggara. Kunci keberhasilan roadshow multi-kota adalah standarisasi produksi yang ketat dan sistem logistik yang handal — kami membangun keduanya sejak tahap perencanaan.',
      },
      {
        _key: 'faq-rs-2',
        question: 'How do you ensure consistent quality at every city stop?',
        questionId: 'Bagaimana Anda memastikan kualitas yang konsisten di setiap kota?',
        answer: 'We develop a standardised production playbook and travel our core team with every programme.',
        answerId: 'Kami mengembangkan playbook produksi standar untuk setiap roadshow — mencakup setup teknis, skrip, panduan briefing tim, dan checklist kualitas. Tim inti kami melakukan perjalanan dengan program; tim lokal di setiap kota di-onboarding menggunakan standar yang sama. Setiap kota mendapat rehearsal teknis sebelum hari-H, bukan perbaikan dadakan.',
      },
      {
        _key: 'faq-rs-3',
        question: 'Can you manage a roadshow that mixes public and private events in the same city?',
        questionId: 'Apakah Anda bisa mengelola roadshow yang menggabungkan acara publik dan privat di kota yang sama?',
        answer: 'Yes. Many of our enterprise roadshows combine formats within a single city.',
        answerId: 'Ya. Banyak roadshow enterprise kami menggabungkan format — misalnya, workshop dealer di pagi hari di satu venue, dilanjutkan peluncuran publik di sore hari di venue berbeda, di kota yang sama. Kami mengelola transisi logistik antar format dan memastikan tim dan materi ada di tempat yang tepat pada waktu yang tepat.',
      },
    ],
  },
  {
    _id: 'service-corporate-event-organizer',
    _type: 'service',
    title: 'Corporate Event Organizer',
    titleId: 'Event Organizer Korporat',
    slug: { _type: 'slug', current: 'corporate-event-organizer' },
    number: '16/16',
    tier: 'tier2',
    descriptor: 'Mitra EO strategis — satu titik akuntabilitas untuk seluruh kalender event Anda.',
    descriptorEn: 'Strategic EO partner — one point of accountability for your entire events calendar.',
    tagline: 'Lebih dari eksekutor — kami adalah mitra strategis Anda.',
    problem: 'Banyak EO yang bisa mengeksekusi acara. Sedikit yang bisa memahami konteks bisnis di baliknya, memberikan perspektif yang menantang brief, dan bertanggung jawab penuh terhadap hasilnya — bukan hanya kehadiran dan dekorasi.',
    approach: 'ELEVENT beroperasi sebagai mitra event organizer strategis — bukan sekadar vendor. Kami membawa perspektif, pengalaman lintas industri, dan jaringan vendor terverifikasi ke setiap engagement, dengan satu titik akuntabilitas dari brief hingga evaluasi pasca-acara.',
    included: [
      'Konsultasi brief dan perencanaan strategis',
      'Manajemen proyek penuh end-to-end',
      'Koordinasi vendor dan subkontraktor',
      'Manajemen anggaran dan pelaporan keuangan',
      'Eksekusi on-site dan manajemen hari-H',
      'Evaluasi dan pelaporan pasca-acara',
      'Akses ke jaringan venue dan vendor terverifikasi ELEVENT',
    ],
    idealFor: 'Perusahaan yang membutuhkan mitra EO jangka panjang yang memahami standar korporat, mampu mengelola kompleksitas enterprise, dan bisa dipercaya untuk merepresentasikan brand mereka di setiap acara.',
    faqs: [
      {
        _key: 'faq-ceo-1',
        question: 'What makes ELEVENT different from other event organizers?',
        questionId: 'Apa yang membedakan ELEVENT dari event organizer lainnya?',
        answer: 'We direct, not just execute. Every brief gets a dedicated specialist team that has run the same format before.',
        answerId: 'Kami mengarahkan, bukan sekadar mengeksekusi. Setiap brief dipasangkan dengan tim spesialis yang sudah berkali-kali menjalankan format yang sama — satu kontak, akuntabilitas penuh dari awal hingga ruangan terakhir ditutup. Kami juga membawa perspektif yang menantang brief Anda, bukan sekadar menyetujuinya.',
      },
      {
        _key: 'faq-ceo-2',
        question: 'Can ELEVENT manage our entire annual events calendar?',
        questionId: 'Bisakah ELEVENT mengelola seluruh kalender acara tahunan kami?',
        answer: 'Yes. We work with several clients as their dedicated annual events partner.',
        answerId: 'Ya. Kami bekerja dengan beberapa klien sebagai mitra acara tahunan khusus mereka — mengelola seluruh portofolio acara dari konferensi besar hingga gathering internal, dengan konsistensi standar dan pengetahuan mendalam tentang brand dan budaya perusahaan yang terakumulasi dari waktu ke waktu.',
      },
      {
        _key: 'faq-ceo-3',
        question: 'What does the onboarding process look like for a long-term EO partnership?',
        questionId: 'Bagaimana proses onboarding jika kami ingin menjadikan Elevent sebagai mitra EO jangka panjang?',
        answer: 'We start with a discovery session to understand your events calendar, brand standards, and internal stakeholders.',
        answerId: 'Kami memulai dengan sesi discovery untuk memahami kalender acara Anda, standar brand, pemangku kepentingan internal, dan ekspektasi. Dari situ, kami menyusun program kemitraan tahunan — termasuk struktur tim, protokol komunikasi, dan proses persetujuan yang disesuaikan dengan cara kerja organisasi Anda. Kebanyakan kemitraan jangka panjang kami dimulai dengan satu acara percontohan terlebih dahulu.',
      },
    ],
  },
]

async function run() {
  // ── STEP 1: Delete all existing service documents ─────────────────
  console.log('\n🗑️   Fetching existing service documents...')
  const existing = await client.fetch<{ _id: string }[]>(
    '*[_type == "service"]{ _id }'
  )
  if (existing.length > 0) {
    console.log(`    Found ${existing.length} existing service(s) — deleting...\n`)
    for (const doc of existing) {
      await client.delete(doc._id)
      console.log(`  🗑️   Deleted ${doc._id}`)
    }
  } else {
    console.log('    No existing services found.\n')
  }

  // ── STEP 2: Import 16 new services ────────────────────────────────
  console.log(`\n📦  Importing ${services.length} services to Sanity...\n`)
  let success = 0
  let failed = 0

  for (const service of services) {
    try {
      await client.createOrReplace(service)
      console.log(`  ✅  ${service.number}  ${service.title}  (${service.slug.current})`)
      success++
    } catch (err) {
      console.error(`  ❌  ${service.title}:`, err)
      failed++
    }
  }

  console.log(`\n✨  Done. ${success} imported, ${failed} failed.\n`)
}

run()
